## ------------ BOOKS
GET http://localhost:5000/api/books

###

GET http://localhost:5000/api/books/5ac29368f1fe314042a060d6

###
POST http://localhost:5000/api/books
content-type: application/json

{
  "name": "YDKJS",
  "cover": "http://some.imagee",
  "owner": "5ac23a4599d6f30e83d344be"
}
 ### 
 
PATCH http://localhost:5000/api/books/5ac29368f1fe314042a060d6
content-type: application/json

{
  "name": "YDKJSSSSSSS"
}
###
DELETE http://localhost:5000/api/books/5ac29368f1fe314042a060d6
