@ressource = users
@id = 5ac37cb389c29431107aa95c

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJib29rcyI6W10sIl9pZCI6IjVhYzM3YzliODljMjk0MzExMDdhYTk1OCIsIm5hbWVGaXJzdCI6InRlc3QiLCJ1c2VybmFtZSI6InRlc3QiLCJuYW1lTGFzdCI6InRlc3QiLCJwYXNzd29yZCI6IiQyYSQxMCRmWHdISi5KeWZHdkJYUXlMdnRiVjhPQ01NaERKLkUxTWFCLmpYU3VVTUZSU1BIaHQ2aG1jRyIsIl9fdiI6MCwiaWQiOiI1YWMzN2M5Yjg5YzI5NDMxMTA3YWE5NTgiLCJpYXQiOjE1MjI3NjA4OTV9.3Wv43aMYVl0NK3B6-_H4xODw4PnQAxsWw38gGfkt8v4
###
GET http://localhost:5000/api/{{ressource}}/

###
GET http://localhost:5000/api/{{ressource}}/{{id}}

###
# POST http://localhost:5000/api/{{ressource}}
# Content-Type: application/json
# Authorization: Bearer {{token}}

# {
#   "nameFirst": "test2",
#   "username": "test2",
#   "nameLast": "test",
#   "password": "123"
# }


 ### 
PATCH http://localhost:5000/api/{{ressource}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "nameFirst": "test",
  "username": "test",
  "nameLast": "fsd"
}
###
DELETE http://localhost:5000/api/{{ressource}}/{{id}}
Authorization: Bearer {{token}}

# Book post
# {
#   "name": "YDKJS",
#   "cover": "http://some.imagee",
#   "owner": "5ac23a4599d6f30e83d344be"
# }

# User post
# {
#   "nameFirst": "test",
#   "username": "test",
#   "nameLast": "test",
#   "password": "123"
# }